version: '3.8'

services:
  backend-go:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - APP_DEBUG=true
      - APP_LOGLEVEL=info
      - DOUBAO_APP_ID=3850845308
      - DOUBAO_ACCESS_TOKEN=iowKNMA-P7ZjwTWKcVoRu_H8pQavteyy
      - QWEN_API_KEY=sk-2f39e33d6b644f3a882811d3049a0217
    restart: unless-stopped
